// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package quiz

import (
	"database/sql"
	"time"
)

type Question struct {
	ID            int32     `json:"id"`
	QuizID        int32     `json:"quiz_id"`
	QuestionText  string    `json:"question_text"`
	OptionA       string    `json:"option_a"`
	OptionB       string    `json:"option_b"`
	OptionC       string    `json:"option_c"`
	OptionD       string    `json:"option_d"`
	CorrectOption string    `json:"correct_option"`
	CreatedAt     time.Time `json:"created_at"`
}

type Quiz struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type UserScore struct {
	ID        int32     `json:"id"`
	QuizID    int32     `json:"quiz_id"`
	UserID    int32     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}
