// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package quiz

import (
	"context"
)

type Querier interface {
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	// query.sql
	CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error)
	GetQuiz(ctx context.Context, id int32) (Quiz, error)
	GetQuizWithQuestions(ctx context.Context, id int32) ([]GetQuizWithQuestionsRow, error)
	ListQuizzes(ctx context.Context) ([]Quiz, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
}

var _ Querier = (*Queries)(nil)
